<a href="https://colab.research.google.com/github/Peter-Thong/machine-learning/blob/master/start_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

In [ ]:
layer_outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):
  neuron_output = 0

  for n_input, weight in zip(inputs, neuron_weights):
    neuron_output += n_input*weight

  neuron_output += neuron_bias
  layer_outputs.append(neuron_output)

print(layer_outputs)

[4.8, 1.21, 2.385]


In [ ]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0


In [ ]:
output = np.dot(inputs, weights) + bias
print(output)

4.8


In [ ]:
np.array([[1, 2, 3]])

array([[1, 2, 3]])

In [ ]:
a = [1, 2, 3]
np.expand_dims(np.array(a), axis=0)

array([[1, 2, 3]])

In [ ]:
a = [1, 2, 3]
b = [2, 3, 4]

a = np.array([a])
b = np.array([b]).T

np.dot(a, b)

array([[20]])

In [ ]:
inputs = [[1.0, 2.0, 3.0, 2.5],
 [2.0, 5.0, -1.0, 2.0],
 [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]


In [ ]:
output = np.dot(inputs, np.array(weights).T) + bias
print(output)

[[ 4.8    0.21   3.885]
 [ 8.9   -2.81   1.7  ]
 [ 1.41   0.051  1.526]]


In [ ]:
inputs = [[1, 2, 3, 2.5], [2., 5., -1., 2], [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
[0.5, -0.91, 0.26, -0.5],
[-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]
weights2 = [[0.1, -0.14, 0.5],
[-0.5, 0.12, -0.33],
[-0.44, 0.73, -0.13]]
biases2 = [-1, 2, -0.5]

In [ ]:
layer1_output = np.dot(inputs, np.array(weights).T) + biases
layer2_output = np.dot(layer1_output, np.array(weights2).T) + biases2

print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [4]:
pip install nnfs


In [5]:
from nnfs.datasets import spiral_data

In [6]:
import numpy as np
import nnfs

nnfs.init()

In [ ]:
print(0.01 * np.random.randn(2, 5))

[[ 0.01764052  0.00400157  0.00978738  0.02240893  0.01867558]
 [-0.00977278  0.00950088 -0.00151357 -0.00103219  0.00410599]]


In [2]:
class Layer_Dense:

  def __init__(self, n_input, n_neurons):
    self.weights = 0.01 * np.random.randn(n_input, n_neurons)
    self.biases = np.zeros((1, n_neurons))

  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

In [7]:
X, y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2, 3)

dense1.forward(X)

print(dense1.output[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]]


In [1]:
#basic of relu in numPY
import numpy as np
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = np.maximum(0, inputs)
print(output)


[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [8]:
# relu activation

class Activation_ReLu:

  def forward(self, inputs):
    self.output = np.maximum(0, inputs)

activation1 = Activation_ReLu()

activation1.forward(dense1.output)

print(activation1.output[:5])

[[0.         0.         0.        ]
 [0.         0.00011395 0.        ]
 [0.         0.00031729 0.        ]
 [0.         0.00052666 0.        ]
 [0.         0.00071401 0.        ]]
